POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "400-400400"
}

# Make sure the person actually exists in the db
# if testing this. No time to code a check for
# existence and then auto-add if not exists in the
# index.js